dashes/urls.py
from .views import dash
from django.urls import path, include
from accounts.views import UserMyPageView

app_name = "dashes"

urlpatterns = [
    # path('dash/<int:pk>', dash, name='dash'),
    path('dash/', dash, name='dash'),
]

nutrition/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('upload.urls')), #upload
    path('dashes/', include('dashes.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path, include
from upload.views import UploadView, UploadDetailView

#해당 네임에서 url patterns에 있는 name의 url로 가주세요~!
app_name = "upload"

urlpatterns = [
    path('', UploadView.as_view(), name='main'), #upload
    path('detail/<int:pk>', UploadDetailView.as_view(), name='detail'),
]

upload/models.py
from django.db import models
from accounts.models import User, Standard
from upload.utils import upload_to_func


class Upload(models.Model):

    BREAKFAST = '아침'
    LUNCH = '점심'
    DINNER = '저녁'

    MEALTIME_CHOICE = (
        (BREAKFAST, '아침'),
        (LUNCH, '점심'),
        (DINNER, '저녁'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='upload_user', blank=True, null=True)
    image = models.ImageField(upload_to=upload_to_func, null=False, max_length=200)
    created_at = models.DateField(auto_now_add=True, null=True)
    mealtimes = models.CharField(choices=MEALTIME_CHOICE, max_length=20)

    def __str__(self):
        return f'{self.user.user_id, self.user.n_code, self.created_at.date(), self.mealtimes}'

    class Meta:
        db_table = 'user_upload_info'

upload/forms.py
from django.forms import ModelForm
from upload.models import Upload


class UserUploadForm(ModelForm):
    class Meta:
        model = Upload
        fields = ['image', 'mealtimes']

upload/views.py
from django.contrib.auth import mixins
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView

from upload.decorator import check_user
from upload.forms import UserUploadForm
from upload.models import Upload
from accounts.models import User, Standard


# def main(request):
#     return render(request, 'upload/main.html')
#
#
# @method_decorator(login_required, 'get')
# @method_decorator(login_required, 'post')
user_required = [login_required, check_user]


@method_decorator(login_required, 'post')
class UploadView(CreateView):
    model = Upload
    form_class = UserUploadForm
    template_name = 'upload/main.html'

    def form_valid(self, form):
        temp_upload = form.save(commit=False)
        temp_upload.user = self.request.user
        print(temp_upload.user.n_code)
        #yolo 함수 추가
        temp_upload.save()
        return super().form_valid(form)

    def get_success_url(self):
        print(self.object.pk, self.object.user)
        return reverse('upload:detail',kwargs={'pk':self.object.pk})
        #이미지 및 class_list (음식명) return 추가

@method_decorator(check_user, 'get')
class UploadDetailView(DetailView):
    model = Upload
    context_object_name = 'upload_result'
    template_name = 'upload/detail.html'

upload/templates/upload/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section>
        <div class="main-text">
            <h2 class="display-5 fw-bolder">{{ upload_result.created_at | date:"m월d일"}}</h2>
            <h4 class="display-5"> {{ upload_result.mealtimes }} 식사 영양정보</h4>
        </div>
        <form action="{% url 'upload:detail' pk=upload_result.pk %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="img-container">
                <div class="wrapper">
                    <div class="image">
                        <img src='{{ upload_result.image.url }}' alt='' />
                    </div>
                    <div id="img-name">File name here</div>
                </div>
                <!-- {#                <input id="default-btn" type="file" hidden>#} -->
                <div class="form-group">
                    <input type="file" hidden name="image" accept="image/*" class="form-control-file" title="" required="" id="default-btn">
                    <button id="custom-btn" class="btn btn-dark">
                        <a class="text-white" style="text-decoration: none;" href="{% url 'upload:main' %}">REPOST</a>
                    </button>
                </div>


                <label for="exampleSelect1" class="form-label5" placeholder="Meal Times"></label>
                <select name=mealtimes id="id_mealtimes" class="form-select" placeholder="Meal Times">
                    <option value="" disabled selected hidden>How many servings did you eat? (General)</option>
                    <option>0.5</option>
                    <option>1.0</option>
                    <option>1.5</option>
                </select>
                <input type="submit" class="btn btn-primary mt-8" id="custom-btn" value="upload">
            </div>
        </form>
        <script src="{% static 'js/upload.js' %}"></script>
    </section>
{% endblock %}

upload/templates/upload/main.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section>
        <div class="main-text">
            <h2 class="display-5 fw-bolder">사진을 업로드 해주세요!</h2>
            <h4 class="display-5">Please upload your pic!</h4>
        </div>
        <form action="{% url 'upload:main' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="img-container">
                <div class="wrapper">
                    <div class="image">
                        <img src='' onerror="this.style.display='none'" alt='' />
                    </div>
                    <div class="content">
                        <div class="file-icon"><i class="fas fa-cloud-upload-alt"></i></div>
                        <div class="file-inner_text">No file chosen, yet!</div>
                    </div>
                    <div id="img-cancle"><i class="fas fa-times"></i></div>
                    <div id="img-name">File name here</div>
                </div>
                <!-- {#                <input id="default-btn" type="file" hidden>#} -->
                <div class="form-group">
                    <input type="file" hidden name="image" accept="image/*" class="form-control-file" title="" required="" id="default-btn">
                    <button onclick ="defaultBtnActive()" id="custom-btn" class="btn btn-dark">Choose a file</button>
                </div>


                <label for="exampleSelect1" class="form-label5" placeholder="Meal Times"></label>
                <select name=mealtimes required id="id_mealtimes" class="form-select" placeholder="Meal Times">
                    <option value="" disabled selected hidden>Meal Time</option>
                    <option>아침</option>
                    <option>점심</option>
                    <option>저녁</option>
                </select>
                <input type="submit" class="btn btn-primary mt-8" id="custom-btn" value="CONFIRM">
            </div>
        </form>
        <script src="{% static 'js/upload.js' %}"></script>
<!-- 
        {#        <script>#}
        {#            const imgName = document.querySelector('#img-name')#}
        {#            const wrapper = document.querySelector('.wrapper')#}
        {#            const defaultBtn = document.querySelector('#default-btn')#}
        {#            const customtBtn = document.querySelector('#custom-btn')#}
        {#            const img = document.querySelector('#custom-btn')#}
        {#            let deleteExp = /[0-9a-zA-Z\^\&\'\@\{\}\[\}\,\$\=\!\-\#\(\)\.\%\+\~\_]+$/;#}
        {#            function defaultBtnActive() {#}
        {#                defaultBtn.click();#}
        {#            }#}
        {#            defaultBtn.addEventListener("change",function (){#}
        {#                const file = this.files[0];#}
        {#                if (file){#}
        {#                    const reader = new FileReader();#}
        {#                    reader.onload = function () {#}
        {#                        const result = reader.result;#}
        {#                        img.src = result;#}
        {#                        wrapper.classList.add(".active");#}
        {#                    }#}
        {#                    reader.readAsDataURL(file)#}
        {#                }#}
        {#                if(this.value){#}
        {#                    let valueStore = this.value.match(deleteExp);#}
        {#                    imgName.textContent#}
        {#                }#}
        {#            });#}
        {#        </script>#} -->
    </section>
{% endblock %}