accounts/urls.py
from django.urls import path, include, re_path
from . import views
from accounts.views import SignUpView, LoginView, log_out, UserMyPageView, UserUpdateView
# from accounts.user_dash import Dash

#해당 네임에서 url patterns에 있는 name의 url로 가주세요~!
app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path('mypage/<int:pk>', UserMyPageView.as_view(), name='detail'),
    path('update/<int:pk>', UserUpdateView.as_view(), name="update"),
    
]

dashes/urls.py
from .views import dash
from django.urls import path, include
from accounts.views import UserMyPageView

app_name = "dashes"

urlpatterns = [
    # path('dash/<int:pk>', dash, name='dash'),
    path('dash/', dash, name='dash'),
]

nutrition/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('upload.urls')), #upload
    path('dashes/', include('dashes.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.hashers import check_password

from . import models
from .models import User

class LoginForm(forms.Form):

    user_id = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "ID"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

    def clean(self):
        user_id = self.cleaned_data.get("user_id")
        password = self.cleaned_data.get("password")
        print(user_id,password)
        try:
            user = models.User.objects.get(user_id=user_id)
            print(user.password)
            if check_password(password,user.password):
                return self.cleaned_data
            else:
                self.add_error("password", forms.ValidationError("Password is wrong"))
        except models.User.DoesNotExist:
            self.add_error("user_id", forms.ValidationError("User does not exist"))

class SignUpForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ("user_id",
                  "password",
                  "password_check",
                  "name",
                  "height",
                  "weight",
                  "age_category",
                  "gender",
                  "activity")
        widgets = {
            "user_id": forms.TextInput(attrs={"placeholder": "ID"}),
            "name": forms.TextInput(attrs={"placeholder": "이름"}),
            "height": forms.TextInput(attrs={"placeholder": "cm" }),
            "weight": forms.TextInput(attrs={"placeholder": "kg"}),
            "age_category": forms.Select(choices=models.User.AGE_CHOICES, attrs={'class': 'form-select'}),
            "gender": forms.Select(choices=models.User.GENDER_CHOICES, attrs={'class': 'form-select'}),
            "activity": forms.Select(choices=models.User.ACTIVITY_CHOISES, attrs={'class': 'form-select'}),
        }

    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password_check = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password confirm"}))

    def clean(self):  # 요청파라미터 값들 조회
        cleaned_data = super().clean() # dictionary 반환.
        password = cleaned_data.get('password')
        password_check = cleaned_data.get('password_check') #password와 password_check 같은지 체크
        if password != password_check:
            self.add_error('password', '비밀번호가 일치하지 않습니다.')
            self.add_error('password_check', '비밀번호가 일치하지 않습니다.') # 이메일(아이디) 중복 체크

class UserUpdateForm(SignUpForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args,**kwargs)

        self.fields['user_id'].disabled = True
        self.fields['name'].disabled = True

class UserChangeForm(forms.ModelForm):
    # 비밀번호 변경 폼
    password = ReadOnlyPasswordHashField(
        label='Password(암호화)'
    )

    class Meta:
        model = User
        fields = ("user_id",
                  "password",
                  "name",
                  "height",
                  "weight",
                  "age_category",
                  "gender",
                  "activity",
                  "n_code",)

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

accounts/views.py
from django.http import HttpResponse
# from accounts.user_dash import Dash
# from . import user_dash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib import messages
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, FormView, DetailView, UpdateView
from . import forms
from .decorator import required
from .models import User, Standard


user_required = [login_required, required]



class LoginView(FormView):

    template_name = "accounts/login.html"
    form_class = forms.LoginForm
    success_url = reverse_lazy("upload:main")

    def form_valid(self, form):
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        user = authenticate(self.request, user_id=user_id, password=password)
        messages.info(self.request, "Welcome!")
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)


def log_out(request):
    messages.info(request, "See you later")
    logout(request)
    return redirect('accounts:login')

class SignUpView(FormView):
    template_name = "accounts/signup.html"
    form_class = forms.SignUpForm
    success_url = reverse_lazy("upload:main")

    def form_valid(self, form):
        temp_user = form.save(commit=False)
        temp_user.n_code = Standard.objects.get(gender=self.request.POST['gender'] , age_category=self.request.POST['age_category'])
        weight = self.request.POST['weight']
        height = self.request.POST['height']
        activity = self.request.POST['activity']
        if self.request.POST['gender'] == 1:
            temp_user.proper_cal = round((66.47 + (13.75 * float(weight)) + (5 * float(height)) - (6.76 * 30))*float(activity))
        else:
            temp_user.proper_cal = round((655.1 + (9.56 * float(weight)) + (1.85 * float(height)) - (4.68 * 30))*float(activity))
        temp_user.save()
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        temp_user.password = make_password(password)
        temp_user.save()
        user = authenticate(user_id=user_id, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

@method_decorator(required, 'get')
class UserMyPageView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accounts/detail.html'


@method_decorator(required, 'get')
@method_decorator(required, 'post')
class UserUpdateView(UpdateView):
    model = User
    template_name = 'accounts/update.html'
    context_object_name = 'target_user'
    form_class = forms.UserUpdateForm


    def form_valid(self, form):
        temp_user = form.save(commit=False)
        weight = self.request.POST['weight']
        height = self.request.POST['height']
        activity = self.request.POST['activity']
        if self.request.POST['gender'] == 1:
            temp_user.proper_cal = round((66.47 + (13.75 * float(weight)) + (5 * float(height)) - (6.76 * 30))*float(activity))
        else:
            temp_user.proper_cal = round((655.1 + (9.56 * float(weight)) + (1.85 * float(height)) - (4.68 * 30))*float(activity))
        user_id = form.cleaned_data.get("user_id")
        password = form.cleaned_data.get("password")
        temp_user.password = make_password(password)
        temp_user.save()
        user = authenticate(user_id=user_id, password=password)
        if user is not None:
            login(self.request, user)
        return super().form_valid(form)

    def get_success_url(self):
        messages.info(self.request, "Success!")
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})
    


    
# 대시앱 만들기
# def dash(request):
#     model = user_dash
#     # messages.info(request, "History_page")
#     # template_name = 'accounts/dash.html'
#     # template_name = 'accounts/dash.html'
#     return render(request, 'accounts/dash.html')


    
    # def dash(request):
    #     messages.info(request, "History페이지")
    #     # dash(request)
    #     return redirect('accounts:dash')
    
    # def post(self,request):
    #     if request.method == "POST":
    #         parent_name = request.POST.get('post')
    #         #parent_name = user
    #         node_parent = None
    #     if parent_name is not None:
    #         node_parent = Node.objects.get(name=parent_name)

    #     Node.objects.create(parent=node_parent)
    # def form_valid(self, form):
    #     # age_category = form.data.get('age_category')
    #     # weight = form.data.get('weight')
    #     # height = form.data.get('weight')
    #     # code = Standard.objects.get(age_category=age_category)
    #     # print(code)
    #     # user = User (
    #     #     n_code=code,
    #     #     proper_cal=float(66.47 + (13.75 * float(weight)) + (5 * float(height)) - (6.76 * 30)),
    #     # )
    #     # # print(user)
    #     # user.save()
    #     print(form)
    #     form.save()
    #     user_id = form.cleaned_data.get('user_id')
    #     password = form.cleaned_data.get('password')
    #     user = authenticate(self.request, user_id=user_id, password=password)
    #     if user is not None:
    #         login(self.request, user)
    #     return super().form_valid(form)
    # def post(self, request):
    #     user_data = json.loads(request.body)
    #     try:
    #
    #         with transaction.atomic():
    #             password = bcrypt.hashpw(user_data['password'].encode('utf-8'), bcrypt.gensalt())
    #
    #             user_model = User(
    #                 account=user_data['account'],
    #                 grade=Grade.objects.get(id=1),
    #                 password=password.decode(),
    #                 name=user_data['name'],
    #                 email=user_data['email'],
    #                 phone=user_data['phone'],
    #                 gender=Gender.objects.get(name=user_data['gender']),
    #                 birthday=user_data['birthday']
    #             )
    #
    #             user_model.save()
    #
    #             # capital area check
    #             Address(
    #                 user=User.objects.get(id=user_model.id),
    #                 address=user_data['address'],
    #                 is_capital_area=self.check_capital_area(user_data['address'])
    #             ).save()
    #
    #             return HttpResponse(status=200)
    #
    #     except KeyError:
    #         return HttpResponse(status=400)
    #
    #     except ValidationError:
    #         return HttpResponse(status=400)



    # if request.method == "POST":
    #     temp = request.POST.get('n_code')
    #     print(temp)
    #     try:
    #         data = json.loads(request.body)
    #         user_id = data['user_id']
    #         password = data['password']
    #         name = data['name']
    #         height = data['height']
    #         weight = data['weight']
    #         age_category = data['age_category']
    #         gender = data['gender']
    #         activity = data['activity']
    #
    #         user = User.objects.create(
    #             user_id=user_id,
    #             password=bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode(),  # hash이후 바로 decode,
    #             name=name,
    #             height=height,
    #             weight=weight,
    #             age_category=age_category,
    #             activity=activity,
    #             gender=gender,
    #             codename=Standard.objects.n_code.filter(Q(gender=gender)),
    #             proper_cal=66.47 + (13.75 * weight) + (5 * height) - (6.76 * 30),
    # #         )
    #         print(user)
    #         return JsonResponse({'MESSAGE': 'SUCCESS TO MAKE ACCOUNT'}, status=201)
    #
    #
    #     except:
    #         return render(request, 'accounts/main.html')


# def add_info(request):
#     if request.method == "POST":
#         temp = request.POST.get("n_code")
#         n_code = Standard.all().filter(Q)

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <diV class="detail_form">
        <h4>My Page</h4>
        {% if target_user == user %}
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">User ID</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.user_id }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Name</label>
                    <input class="form-control" id="disabledInput" type="password" placeholder="{{ target_user.name }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Height</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.height }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Weight</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.weight }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Age category</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.age_category }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Gender</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.gender }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Activity</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.activity }}" disabled="">
                </fieldset>
            </div>
            <div class="detail">
                <fieldset disabled="">
                    <label class="form-label" for="disabledInput">Proper. Kcal</label>
                    <input class="form-control" id="disabledInput" type="text" placeholder="{{ target_user.proper_cal }}" disabled="">
                </fieldset>
            </div>
        {% endif %}
        {% if target_user == user %}
            <div>
                <button class="btn btn-primary mt-4 mb-4" id="custom-btn">
                    <a class="text-white" style="text-decoration: none;" href="{% url 'accounts:update' pk=user.pk %}">CHANGE INFO</a>
                </button>
            </div>
        {% endif %}




    </div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="login_form">
        <div>
           <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" id="custom-btn" class="btn btn-primary mt-4 mb-4" value="LOGIN">
            </form>
        </div>
    </div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="signup-form">
        <h2>Sing Up</h2>
        <form class="" action="{% url 'accounts:signup' %}" method="post">
            {% csrf_token %}
{#            {% for i in form %}#}
            {% bootstrap_form form %}
{#            {{ i.label_tag }} {{ i }}#}
{#            {% endfor %}#}
            <input id="custom-btn" type="submit" class="btn btn-primary mt-4 mb-4" value="SIGN UP">
        </form>
    {{ post }}
    </div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div class="update-form">

        <h4>Change Info</h4>
        <form action="{% url 'accounts:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" id="custom-btn" class="btn btn-primary mt-4 mb-4" value="SAVE">
        </form>

    </div>

{% endblock %}