accounts/urls.py
from django.urls import path, include, re_path
from . import views
from accounts.views import SignUpView, LoginView, log_out, UserMyPageView, UserUpdateView
# from accounts.user_dash import Dash

#해당 네임에서 url patterns에 있는 name의 url로 가주세요~!
app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),

    path('mypage/<int:pk>', UserMyPageView.as_view(), name='detail'),
    path('update/<int:pk>', UserUpdateView.as_view(), name="update"),
    
]

dashes/urls.py
from .views import dash
from django.urls import path, include
from accounts.views import UserMyPageView

app_name = "dashes"

urlpatterns = [
    # path('dash/<int:pk>', dash, name='dash'),
    path('dash/', dash, name='dash'),
]

nutrition/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('upload.urls')), #upload
    path('dashes/', include('dashes.urls')),
    path('django_plotly_dash/', include('django_plotly_dash.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path, include
from upload.views import UploadView, UploadDetailView

#해당 네임에서 url patterns에 있는 name의 url로 가주세요~!
app_name = "upload"

urlpatterns = [
    path('', UploadView.as_view(), name='main'), #upload
    path('detail/<int:pk>', UploadDetailView.as_view(), name='detail'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}

<body>

{% include 'header.html' %}
{% if messages %}
    {% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" id="splash" role="alert">
            <strong> {{ msg }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        <script>
            // const splash = document.getElementById('splash');
            // const sDiv = splash.getElementsByTagName("div");
            // setTimeout(function () {
            //    splash.slideUp();
            // });
            $( 'div.alert' ).show( function() {
                $( 'strong' ).fadeOut(2500);
                $( 'div.alert' ).slideUp(2000) && $( 'div.alert' ).hide(1800);;


            } );

        </script>
    {% endfor %}
{% endif %}
{% block content %}
{% endblock %}
{% include 'footer.html' %}

</body>

</html>

templates/footer.html
{#<footer class="py-5 bg-light fixed-bottom">#}
{#    <div class="container"><p class="m-0 text-center text-dark">Copyright &copy; MultiCampus Project</p></div>#}
{#</footer>#}

<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item">About</li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">Contact</li>
                    <li class="list-inline-item">⋅</li>
                    <li class="list-inline-item">Privacy Policy</li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">&copy; Multicampus 2021. All Rights Reserved.</p>
            </div>
            <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                <ul class="list-inline mb-0">
                    <li class="list-inline-item me-4">
                        <a href="#"><i class="fab fa-github fa-2x"></i></a>
                    </li>
                    <li class="list-inline-item me-4">
                        <a href="#"><i class="fab fa-instagram fa-2x"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#"><i class="fab fa-twitter fa-2x"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

templates/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Project | 영양정보</title>
    <!-- CSS Link-->
    <link rel="stylesheet" href="{% static 'style.css' %}?ver1" />



    <!-- Bootstrap Link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6478f529f2.js" crossorigin="anonymous"></script>
    <!-- Jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Google fonts Link -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700;800&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Playfair+Display&display=swap" rel="stylesheet">

</head>

templates/header.html
{% load static %}
<!-- Navigation-->

{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#!">오로나민C조</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
            <ul class="navbar-nav">

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'upload:main' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashes:dash' %}">History</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-signup">
                    <a class="btn btn-primary ml-auto mr-1" href="{% url 'accounts:signup' %}">Sign Up</a>
                    {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
                <li class="nav-signup">
                    <a class="btn btn-primary ml-auto mr-1" href="{% url 'accounts:detail' pk=user.pk %}">My Page</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>